sources:
  - name: DAOmocracy
    handler:
      graphql:
        endpoint: https://api.studio.thegraph.com/query/50862/daomocracy/v0.0.38

documents:
  - ./queries/election-query.graphql
  - ./queries/daos-query.graphql
  - ./queries/dao-query.graphql
  - ./queries/proposal-query.graphql