[profile.default]
src = 'contracts'
out = 'out'
libs = ['lib']
remappings = [
    '@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/',
    "@chainlink/contracts/=node_modules/@chainlink/contracts",
    '@chainlink/contracts-ccip/=node_modules/@chainlink/contracts-ccip',
]
fs_permissions = [{ access = "read-write", path = "./" }]

[rpc_endpoints]
default_network = "http://127.0.0.1:8545"
localhost = "http://127.0.0.1:8545"

ethereumSepolia = "https://eth-sepolia.g.alchemy.com/v2/${ALCHEMY_API_KEY}"
optimismGoerli = "https://opt-goerli.g.alchemy.com/v2/${ALCHEMY_API_KEY}"
polygonMumbai = "https://polygon-mumbai.g.alchemy.com/v2/${ALCHEMY_API_KEY}"

# [etherscan]
# optimismGoerli = { key = "${ ETHERSCAN_OPTIMISM_KEY }", url = "https://api-goerli-optimistic.etherscan.io/" }
# polygonMumbai = { key = "${ ETHERSCAN_MUMBAI_KEY }", url = "https://api-testnet.polygonscan.com/" }

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
